"use client";

import React, { useState } from "react";

const MissionVision = () => {
  // State for image sliders
  const [mosesSlideIndex, setMosesSlideIndex] = useState(0);
  const [tanzaniaSlideIndex, setTanzaniaSlideIndex] = useState(0);
  const [teresaSlideIndex, setTeresaSlideIndex] = useState(0);
  const [kpapSlideIndex, setKpapSlideIndex] = useState(0);

  // Image arrays for sliders
  const mosesImages = [
    "/img/charities/m11.png",
    "/img/charities/m1.png",
    "/img/charities/m2.png",
    "/img/charities/m3.png",
    "/img/charities/m11.png",
    "/img/charities/m22.png",
  ];

  const tanzaniaImages = ["/img/charities/mm1.png", "/img/charities/mm2.png"];

  const teresaImages = ["/img/team/1/tel1.png", "/img/team/1/tek11.png"];

  const kpapImages = ["/img/team/1/kpap2.png", "/img/team/1/kpap2.png"];

  // Navigation functions
  const nextSlide = (current, setCurrent, maxLength) => {
    setCurrent((current + 1) % maxLength);
  };

  const prevSlide = (current, setCurrent, maxLength) => {
    setCurrent((current - 1 + maxLength) % maxLength);
  };

  return (
    <section className="layout-pt-md layout-pb-md">
      <div className="container">
        {/* Charity Partner Sections */}
        <div className="row justify-center text-center mb-40">
          <div className="col-auto">
            <h2 className="text-30 md:text-24">Help Us, To Help Them</h2>
          </div>
        </div>

        {/* Moses Comfort Home Foundation */}
        <div
          className="row y-gap-30 items-center pb-60"
          style={{
            backgroundColor: "#f8f8f8",
            borderRadius: "12px",
            marginBottom: "60px",
          }}
        >
          <div className="col-lg-5">
            <div className="relative" style={{ height: "400px" }}>
              <img
                src={mosesImages[mosesSlideIndex]}
                alt="Moses Comfort Home Foundation"
                className="rounded-4 w-100 object-cover"
                style={{ height: "100%" }}
              />

              {/* Navigation Arrows */}
              <div className="absolute-full-center d-flex justify-between">
                <button
                  onClick={() =>
                    prevSlide(
                      mosesSlideIndex,
                      setMosesSlideIndex,
                      mosesImages.length
                    )
                  }
                  className="d-flex items-center justify-center size-50 rounded-full bg-white shadow-1"
                  style={{ marginLeft: "-25px" }}
                >
                  <i
                    className="icon-arrow-left text-16"
                    style={{ color: "#31a046" }}
                  ></i>
                </button>

                <button
                  onClick={() =>
                    nextSlide(
                      mosesSlideIndex,
                      setMosesSlideIndex,
                      mosesImages.length
                    )
                  }
                  className="d-flex items-center justify-center size-50 rounded-full bg-white shadow-1"
                  style={{ marginRight: "-25px" }}
                >
                  <i
                    className="icon-arrow-right text-16"
                    style={{ color: "#31a046" }}
                  ></i>
                </button>
              </div>

              {/* Slide Indicators */}
              <div className="absolute bottom-20 w-100 d-flex justify-center gap-10">
                {mosesImages.map((_, index) => (
                  <div
                    key={`moses-dot-${index}`}
                    className={`size-10 rounded-full ${
                      mosesSlideIndex === index ? "bg-white" : "bg-white-50"
                    }`}
                    onClick={() => setMosesSlideIndex(index)}
                    style={{ cursor: "pointer" }}
                  ></div>
                ))}
              </div>
            </div>
          </div>

          <div className="col-lg-7">
            <div className="px-40 py-40 md:px-30 md:py-30 sm:px-20 sm:py-20">
              <h3 className="text-26 fw-600 text-dark-1 mb-15">
                Our Partner Charity Moses Comfort Home Foundation Project in
                Arusha
              </h3>
              <p className="text-dark-1 mt-20">
                The idea of this project was generated by BIBI MKWAYA IKINDA
                MASANJA when she did some research concerning street and
                vulnerable children living in poor conditions.
              </p>
              <p className="text-dark-1 mt-15">
                She discovered that the situation is often due to poverty, loss
                of a parent and lack of guardians to value these children. "If
                they are not valued than they are deprived of their basic
                rights." Bibi has given them physical and spiritual health for
                their future development and a safe and loving home.
              </p>
              <div className="mt-30">
                <a
                  href="https://mosescomforthome.org"
                  className="button -md -blue-1 text-white"
                  style={{ backgroundColor: "#31a046" }}
                >
                  Find Out More
                </a>
              </div>
            </div>
          </div>
        </div>

        {/* Help Tanzania Children's Home */}
        <div
          className="row y-gap-30 items-center pb-60"
          style={{
            backgroundColor: "#edf7ee",
            borderRadius: "12px",
            marginBottom: "60px",
          }}
        >
          <div className="col-lg-5">
            <div className="relative" style={{ height: "400px" }}>
              <img
                src={tanzaniaImages[tanzaniaSlideIndex]}
                alt="Help Tanzania Children's Home"
                className="rounded-4 w-100 object-cover"
                style={{ height: "100%" }}
              />

              {/* Navigation Arrows */}
              <div className="absolute-full-center d-flex justify-between">
                <button
                  onClick={() =>
                    prevSlide(
                      tanzaniaSlideIndex,
                      setTanzaniaSlideIndex,
                      tanzaniaImages.length
                    )
                  }
                  className="d-flex items-center justify-center size-50 rounded-full bg-white shadow-1"
                  style={{ marginLeft: "-25px" }}
                >
                  <i
                    className="icon-arrow-left text-16"
                    style={{ color: "#31a046" }}
                  ></i>
                </button>

                <button
                  onClick={() =>
                    nextSlide(
                      tanzaniaSlideIndex,
                      setTanzaniaSlideIndex,
                      tanzaniaImages.length
                    )
                  }
                  className="d-flex items-center justify-center size-50 rounded-full bg-white shadow-1"
                  style={{ marginRight: "-25px" }}
                >
                  <i
                    className="icon-arrow-right text-16"
                    style={{ color: "#31a046" }}
                  ></i>
                </button>
              </div>

              {/* Slide Indicators */}
              <div className="absolute bottom-20 w-100 d-flex justify-center gap-10">
                {tanzaniaImages.map((_, index) => (
                  <div
                    key={`tanzania-dot-${index}`}
                    className={`size-10 rounded-full ${
                      tanzaniaSlideIndex === index ? "bg-white" : "bg-white-50"
                    }`}
                    onClick={() => setTanzaniaSlideIndex(index)}
                    style={{ cursor: "pointer" }}
                  ></div>
                ))}
              </div>
            </div>
          </div>

          <div className="col-lg-7">
            <div className="px-40 py-40 md:px-30 md:py-30 sm:px-20 sm:py-20">
              <h3 className="text-26 fw-600 text-dark-1 mb-15">
                Help Tanzania's Children's Home (The Stable Life For Tanzanian
                Kids Foundation)
              </h3>
              <p className="text-dark-1 mt-20">
                Help Tanzania Children's Home came into existence as a result of
                the motivation and personal initiative of Mr. Ogutu Ouamah
                Joseph to enhance the social-economic status of the
                underprivileged children. Hailing from rural family, the founder
                was no stranger to the hardships faced by underprivileged
                children.
              </p>
              <p className="text-dark-1 mt-15">
                With the help and economic blessings from a elder society
                leader, the founder set out to do his best to make a positive
                difference in the lives of fellow underprivileged children.
              </p>
              <div className="mt-30">
                <a
                  href="https://helptnchildrenhome.org"
                  className="button -md -blue-1 text-white"
                  style={{ backgroundColor: "#31a046" }}
                >
                  Find Out More
                </a>
              </div>
            </div>
          </div>
        </div>

        {/* Founder Section */}
        <div className="row justify-center text-center mb-40">
          <div className="col-auto">
            <h2 className="text-30 md:text-24">
              Founder of Superior Kilimanjaro and Safaris
            </h2>
          </div>
        </div>

        <div
          className="row y-gap-30 items-center pb-60"
          style={{
            backgroundColor: "#f0f8f0",
            borderRadius: "12px",
            marginBottom: "60px",
          }}
        >
          <div className="col-lg-4">
            <div className="relative" style={{ height: "500px" }}>
              <img
                src="/img/team/1/mike.png"
                alt="Michael Prentice - Founder"
                className="rounded-4 w-100 object-cover"
                style={{ height: "100%" }}
              />
            </div>
            <div className="text-center mt-20">
              <h3 className="text-22 fw-600">Michael Prentice</h3>
              <p className="text-16 mt-5">Founder</p>
            </div>
          </div>

          <div className="col-lg-8">
            <div className="px-40 py-40 md:px-30 md:py-30 sm:px-20 sm:py-20">
              <p className="text-dark-1 leading-relaxed">
                Founder, Michael Prentice was born and raised in the heart of
                the North Devon Countryside 'in the middle of nowhere' near
                Exmoor.
              </p>

              <p className="text-dark-1 leading-relaxed mt-15">
                "My love of nature, wildlife and the countryside environment
                grew with me growing up."
              </p>

              <p className="text-dark-1 leading-relaxed mt-15">
                "My love of adventure, nature, exploration and hill walking led
                me to take part in different challenges like the Duke of
                Edinburgh's Award Scheme and the Ten Tors treks across Dartmoor
                as a young man. In my 20's and 30's while I was in the Services
                I was heavily involved in various sports. I took part in running
                marathons and half marathons for charity and often trained in
                the local hills. I met Abdallah in Tanzania whilst trekking in
                the Kilimanjaro National Park and a friendship formed with our
                mutual interests and experience. Superior Kilimanjaro and
                Safaris was formed from this friendship, offering other like
                minded people treks and safaris in the exhilarating landscapes
                of this part of Africa. Our company prides itself on providing a
                comprehensive and good quality service from start to finish. We
                are also proud of the fact that 5% of our profits go to a 'Moses
                Comfort Home Foundation' and 'Help Tanzania's Children's Home'
                charities in Arusha.
              </p>

              <div className="mt-30">
                <h4 className="text-18 fw-600">
                  By Invite From The Queen.....
                </h4>
                <p className="text-dark-1 leading-relaxed mt-10">
                  Michael was invited by the Queen to Buckingham Palace for
                  Services to charities in 2007. Supporting charities has always
                  been a large part of Michael's life. Now supporting amongst
                  others 'Moses Comfort Home Foundation' and 'Help Tanzania's
                  Children's Home' charities in Arusha.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Head Guide Section */}
        <div className="row justify-center text-center mb-40">
          <div className="col-auto">
            <h2 className="text-30 md:text-24">Head Guide</h2>
          </div>
        </div>

        <div
          className="row y-gap-30 items-center pb-60"
          style={{
            backgroundColor: "#f5f9f5",
            borderRadius: "12px",
            marginBottom: "60px",
          }}
        >
          <div className="col-lg-4">
            <div className="relative" style={{ height: "500px" }}>
              <img
                src="/img/team/1/ab.png"
                alt="Abdallah Msuya - Co-Founder and Head Guide"
                className="rounded-4 w-100 object-cover"
                style={{ height: "100%" }}
              />
            </div>
            <div className="text-center mt-20">
              <h3 className="text-22 fw-600">Abdallah Msuya</h3>
              <p className="text-16 mt-5">Co-Founder and Head Guide</p>
            </div>
          </div>

          <div className="col-lg-8">
            <div className="px-40 py-40 md:px-30 md:py-30 sm:px-20 sm:py-20">
              <p className="text-dark-1 leading-relaxed">
                Abdallah has been to the summit of Kilimanjaro over 250 times
                taking up able bodied trekkers and those facing challenges
                navigating disabilities including wheelchair users and
                individuals with blindness. Abdallah started working as a porter
                at the age of 18 years old then rose to a guide then progressed
                on to being a head guide with some of the biggest Kilimanjaro
                tour companies.
              </p>

              <p className="text-dark-1 leading-relaxed mt-15">
                He is a qualified Wellness First Aid Responder (WFR); he holds a
                Hiking Guide Licence; a Safari Guide Licence and speaks good
                English, Spanish and Swahili. He can also converse in a basic
                level in other languages. Abdallah put his boyhood dream into
                motion and set out to create his own company which he has now
                been able to do with the help from the UK's Michael Prentice
                after the two formed a friendship after meeting in Kilimanjaro
                National Park.
              </p>

              <p className="text-dark-1 leading-relaxed mt-15 font-italic">
                'Since my childhood, I have been discovering, exploring and
                developing my love for nature such as mountains and National
                parks.'
              </p>

              <p className="text-dark-1 leading-relaxed mt-15">
                As time passed, my passion for the mountains and safaris led me
                to pursue carrier as a tour guide. Moreover, to hike at Mount
                Kilimanjaro at 5895 meters, with trekkers from all all over the
                world makes me feel very privileged. Ultimately, it is the most
                amazing feeling that I like to bring to my clients every time we
                go for exploring nature. My aim is to provide a positive
                experience and assist tourists in achieving their goal.
              </p>

              <p className="text-dark-1 leading-relaxed mt-15 font-italic">
                "It is about having immense fun while exploring nature."
              </p>
            </div>
          </div>
        </div>

        {/* Marketing & PR Manager Section */}
        <div className="row justify-center text-center mb-40">
          <div className="col-auto">
            <h2 className="text-30 md:text-24">Our Marketing and PR Manager</h2>
          </div>
        </div>

        <div
          className="row y-gap-30 items-center pb-60"
          style={{
            backgroundColor: "#edf7ee",
            borderRadius: "12px",
            marginBottom: "60px",
          }}
        >
          <div className="col-lg-4">
            <div className="relative" style={{ height: "500px" }}>
              <img
                src={teresaImages[teresaSlideIndex]}
                alt="Teresa Anderson - Marketing and PR Manager"
                className="rounded-4 w-100 object-cover"
                style={{ height: "100%" }}
              />

              {/* Navigation Arrows */}
              <div className="absolute-full-center d-flex justify-between">
                <button
                  onClick={() =>
                    prevSlide(
                      teresaSlideIndex,
                      setTeresaSlideIndex,
                      teresaImages.length
                    )
                  }
                  className="d-flex items-center justify-center size-50 rounded-full bg-white shadow-1"
                  style={{ marginLeft: "-25px" }}
                >
                  <i
                    className="icon-arrow-left text-16"
                    style={{ color: "#31a046" }}
                  ></i>
                </button>

                <button
                  onClick={() =>
                    nextSlide(
                      teresaSlideIndex,
                      setTeresaSlideIndex,
                      teresaImages.length
                    )
                  }
                  className="d-flex items-center justify-center size-50 rounded-full bg-white shadow-1"
                  style={{ marginRight: "-25px" }}
                >
                  <i
                    className="icon-arrow-right text-16"
                    style={{ color: "#31a046" }}
                  ></i>
                </button>
              </div>

              {/* Slide Indicators */}
              <div className="absolute bottom-20 w-100 d-flex justify-center gap-10">
                {teresaImages.map((_, index) => (
                  <div
                    key={`teresa-dot-${index}`}
                    className={`size-10 rounded-full ${
                      teresaSlideIndex === index ? "bg-white" : "bg-white-50"
                    }`}
                    onClick={() => setTeresaSlideIndex(index)}
                    style={{ cursor: "pointer" }}
                  ></div>
                ))}
              </div>
            </div>
            <div className="text-center mt-20">
              <h3 className="text-22 fw-600">Teresa J Anderson</h3>
              <p className="text-16 mt-5">Marketing and PR Manager</p>
            </div>
          </div>

          <div className="col-lg-8">
            <div className="px-40 py-40 md:px-30 md:py-30 sm:px-20 sm:py-20">
              <p className="text-dark-1 leading-relaxed">
                Teresa Anderson, our dedicated Marketing and PR Manager, brings
                a wealth of experience to our team. With a genuine love for the
                children at our sponsored orphanages, Teresa has visited them on
                several occasions, forming meaningful connections. As SKAS
                grows, she envisions a future where we can offer training
                programs for these children when they turn 18. Preparing them
                for careers as Kilimanjaro Guides, Porters, Safari Guides,
                Chefs, Drivers, and Marketing Executives. Together, we can
                empower the next generation and contribute to their bright
                futures.
              </p>

              <p className="text-dark-1 leading-relaxed mt-15">
                Teresa is eager to connect with anyone planning a Kilimanjaro
                Trek for charity. 'At SKAS, we love to showcase your efforts and
                support your cause by highlighting your journey on our social
                media pages and website. Reach out to us, and let's share your
                inspiring adventure!'
              </p>

              <p className="text-dark-1 leading-relaxed mt-15 font-italic">
                "My role at SKAS is the most fulfilling role I have ever taken
                on, I have been very privileged in being able to get know the
                children and the staff at the orphanages"
              </p>

              <div className="mt-30 p-20 bg-white rounded-4">
                <h4 className="text-18 fw-600">Meeting with Kate Humble</h4>
                <p className="text-dark-1 leading-relaxed mt-10">
                  Teresa had an engaging conversation with Kate Humble, the
                  renowned BBC presenter and wildlife expert, about the
                  breathtaking safaris in Africa, particularly in the Serengeti.
                  During their discussion, Kate expressed gratitude for the
                  incredible work that Superior Kilimanjaro and Safaris are
                  doing to support orphanages in Arusha. Their shared passion
                  for wildlife and community upliftment made for a truly
                  inspiring exchange.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* KPAP Section */}
        <div className="row justify-center text-center mb-40">
          <div className="col-auto">
            <h2 className="text-30 md:text-24">
              Kilimanjaro Porters Assistance Project (KPAP)
            </h2>
          </div>
        </div>

        <div
          className="row y-gap-30 items-center pb-60"
          style={{
            backgroundColor: "#f8f5e6",
            borderRadius: "12px",
            marginBottom: "60px",
          }}
        >
          <div className="col-lg-5">
            <div className="relative" style={{ height: "400px" }}>
              <img
                src={kpapImages[kpapSlideIndex]}
                alt="Kilimanjaro Porters Assistance Project"
                className="rounded-4 w-100 object-cover"
                style={{ height: "100%" }}
              />

              {/* Navigation Arrows */}
              <div className="absolute-full-center d-flex justify-between">
                <button
                  onClick={() =>
                    prevSlide(
                      kpapSlideIndex,
                      setKpapSlideIndex,
                      kpapImages.length
                    )
                  }
                  className="d-flex items-center justify-center size-50 rounded-full bg-white shadow-1"
                  style={{ marginLeft: "-25px" }}
                >
                  <i
                    className="icon-arrow-left text-16"
                    style={{ color: "#31a046" }}
                  ></i>
                </button>

                <button
                  onClick={() =>
                    nextSlide(
                      kpapSlideIndex,
                      setKpapSlideIndex,
                      kpapImages.length
                    )
                  }
                  className="d-flex items-center justify-center size-50 rounded-full bg-white shadow-1"
                  style={{ marginRight: "-25px" }}
                >
                  <i
                    className="icon-arrow-right text-16"
                    style={{ color: "#31a046" }}
                  ></i>
                </button>
              </div>

              {/* Slide Indicators */}
              <div className="absolute bottom-20 w-100 d-flex justify-center gap-10">
                {kpapImages.map((_, index) => (
                  <div
                    key={`kpap-dot-${index}`}
                    className={`size-10 rounded-full ${
                      kpapSlideIndex === index ? "bg-white" : "bg-white-50"
                    }`}
                    onClick={() => setKpapSlideIndex(index)}
                    style={{ cursor: "pointer" }}
                  ></div>
                ))}
              </div>
            </div>
          </div>

          <div className="col-lg-7">
            <div className="px-40 py-40 md:px-30 md:py-30 sm:px-20 sm:py-20">
              <p className="text-dark-1 leading-relaxed">
                One of the best known initiatives of KRTO is the Partner for
                Responsible Travel Program. The monitoring of the program is
                organized by the Kilimanjaro Porter Assistance project (KPAP).
                We have two other important projects: Kilimanjaro Environmental
                Care Awareness (KECA) and Community Empowerment and Development
                (CED).
              </p>

              <div className="mt-30">
                <h4 className="text-18 fw-600">Lending mountain clothing</h4>
                <p className="text-dark-1 leading-relaxed mt-10">
                  KRTO receives donated mountain equipment from climbers and
                  organizations. This gear is available free of charge for a
                  loan to porters and mountain crew who cannot afford the proper
                  climbing equipment. By stamping all donated clothing with a
                  KPAP label and requiring an item of value (phone, bicycle) to
                  serve as a deposit from the those who borrow, KPAP has a
                  clothing return rate of over 90% since 2003.
                </p>
                <p className="text-dark-1 leading-relaxed mt-10">
                  All mountain crew are welcome to borrow gear from the (free of
                  charge) lending program.
                </p>
              </div>

              <div className="mt-30">
                <h4 className="text-18 fw-600">
                  Advocating for fair treatment
                </h4>
                <p className="text-dark-1 leading-relaxed mt-10">
                  Promoting climbing company with responsible treatment
                  practices
                </p>
                <p className="text-dark-1 leading-relaxed mt-10">
                  Via KPAP activities the organisation promotes climbers to
                  choose one of the companies with responsible treatment
                  practices. Providing educational opportunities. KPAP organises
                  free educational programs and training classes for porters and
                  crews about:
                </p>
                <ul className="mt-10 pl-20">
                  <li className="text-dark-1 mt-5">
                    Budgeting & Money Management (1,957)
                  </li>
                  <li className="text-dark-1 mt-5">
                    Through funding provided by the Tanzanian Foundation for
                    Civil Society, KPAP has instructed 5,225 porters in classes
                    on Porter Rights
                  </li>
                  <li className="text-dark-1 mt-5">
                    1,387 mountain crew have been certified in First Aid
                  </li>
                  <li className="text-dark-1 mt-5">
                    84 porters and guides have been trained as First Aid
                    Instructors
                  </li>
                  <li className="text-dark-1 mt-5">
                    Vaccine Education Class: 620
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default MissionVision;
